dataset:
  path: ../input/ventilator-pressure-prediction
  lstm1: ventilator_lstm_model.csv
  lstm2: gb-vpp-median-lstm.csv
  lightgbm: 10fold_stacking_lightgbm.csv

weight:
  w1: 0.333
  w2: 0.334
  w3: 0.333

submit:
  path: ../submit
  name: nn_lgbm_ensemble.csv
