dataset:
  path: ../input/ventilator-pressure-prediction
  lstm1: ventilator_lstm_model.csv
  lstm2: gb-vpp-lstm.csv
  lightgbm: median_stacking_lightgbm.csv

weight:
  w1: 0.333
  w2: 0.334
  w3: 0.333

submit:
  path: ../submit
  name: nn_lgbm_ensemble.csv
