dataset:
  path: ../input/ventilator-pressure-prediction
  lstm1: gb-vpp-median-lstm.csv
  lstm2: ventilator_lstm_model.csv
  lightgbm: five_model_lightgbm_preds.csv
  ensemble: lb_ensemble.csv
weight:
  w1: 0.333
  w2: 0.334
  w3: 0.333

submit:
  path: ../submit
  name: nn_lgbm_ensemble.csv
