dataset:
  path: ../input/ventilator-pressure-prediction
  test: test.csv
  train: train.csv
  submit: sample_submission.csv

model:
  fold: 5
  verbose: 1000

params:
  n_estimators: 30000
  boosting_type: gbdt
  learning_rate: 0.3749080237694725
  num_leaves: 999
  objective: mae
  max_depth: 13
  max_bin: 819
  min_child_samples: 23
  reg_alpha: 0.02403950683025824
  reg_lambda: 0.015227525095137952
  n_jobs: -1

submit:
  path: ../submit
  name: 5fold_lightgbm.csv
