dataset:
  path: ../input/ventilator-pressure-prediction
  test: test.csv
  train: train.csv
  submit: sample_submission.csv

model:
  fold: 5
  verbose: 1000

params:
  boosting_type: gbdt
  colsample_bytree: 0.3
  learning_rate: 0.35
  n_estimators: 30000
  num_leaves: 10000
  objective: mae
  min_child_samples: 30
  max_bin: 600
  subsample: 0.8
  random_state: 42
  n_jobs: -1

submit:
  path: ../submit
  name: 5fold_lightgbm.csv
