dataset:
  path: ../input/ventilator-pressure-prediction
  test: test.csv
  train: train.csv
  submit: sample_submission.csv
  num: 11

model:
  fold: 5
  verbose: 1000

params:
  n_estimators: 30000
  boosting_type: gbdt
  learning_rate: 0.3363649934414201
  num_leaves: 606
  objective: mae
  max_depth: 7
  max_bin: 781
  min_child_samples: 37
  reg_alpha: 0.036210622617823776
  reg_lambda: 0.06506676052501416
  n_jobs: -1

submit:
  path: ../submit
  name: 5fold_lightgbm.csv
