dataset:
  path: ../input/ventilator-pressure-prediction
  test: test.csv
  train: train.csv
  submit: sample_submission.csv

model:
  fold: 5
  verbose: 1000

params:
  boosting_type: gbdt
  colsample_bytree: 0.2788441133807552
  learning_rate: 0.5
  max_depth: 4
  n_estimators: 20000
  num_leaves: 31
  objective: mae
  reg_alpha: 0.219772826786357
  reg_lambda: 0.6709557931179373
  subsample: 0.8339152856093507
  random_state: 2021
  n_jobs: -1

submit:
  path: ../submit
  name: 5fold_lightgbm.csv