dataset:
  path: ../input/ventilator-pressure-prediction
  test: test.csv
  train: train.csv
  submit: sample_submission.csv

model:
  fold: 5
  verbose: 1000

params:
  boosting_type: gbdt
  learning_rate: 0.3
  num_leaves: 1024
  objective: regression
  metric: mae
  min_child_samples: 32
  n_jobs: -1

submit:
  path: ../submit
  name: 5fold_lightgbm.csv
