dataset:
  path: ../input/ventilator-pressure-prediction
  lightgbm: stacking_all_we_need.csv
  lstm1: pulp_fiction_preds.csv
  lstm2: dnn_lstm_preds.csv
  lstm3: dnn_lstm_preds2.csv
  lstm4: lstm_resnet_preds.csv
  lstm5: pulp_fiction_preds2.csv
  lstm6: ver10_lstm_preds.csv


submit:
  path: ../submit
  name: nn_lgbm_ensemble.csv
